num_classes: 10
epochs: 100
grad_clip: -1
log_frequency: 100

model:
  name: RobustWideResNet
  channel_configs: [16, 160, 320, 640]
  depth_configs: [5, 5, 5]
  drop_rate_config: [0.0, 0.0, 0.0]
  num_classes: 10
  stride_config: [1, 2, 2]

criterion:
  name: MART
  step_size: 0.007843137254901960784314
  epsilon: 0.03137254901960784313725
  perturb_steps: 10

optimizer:
  name: SGD
  lr: 0.1
  weight_decay: 5.e-4
  momentum: 0.9

scheduler:
  name: MultiStepLR
  milestones: [75, 90, 100]
  gamma: 0.1

dataset:
  name: DatasetGenerator
  train_bs: 128
  eval_bs: 256
  n_workers: 4
  train_d_type: 'CIFAR10'
  test_d_type: 'CIFAR10'
  train_tf_op: 'CIFAR10'
  test_tf_op: 'CIFAR10'
  train_path: './data/projects/punim0784/datasets/'
  test_path: './data/projects/punim0784/datasets/'
